name: java-pipeline
on:
  workflow_dispatch:

  push:
    branches: [master]
  
jobs:
  java-setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: java-runtime-setup
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: checking java version  
        run: java -version

            

