name: pr-validation
on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]

jobs:
  validate: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: pr-validation
        run: echo pr is validated