name: path-filter
on:
  push:
    branches: [master]
    path:
      - src/**
jobs:
  path-based-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: path-validation
        run: echo path based push done


